[pytest]
pythonpath = .
addopts = -v --tb=short

markers = 
    gameplay: тест самой игры, и геймплея
    input_invalid_values: тестирование при невалидных значениях
    utils: тест вспомогательных утилит (Game/Gameplay_tools)

norecursedirs = build dist .pytest_cache cache/pytest_cache .venv .git
cache_dir = cache/pytest_cache
