name: Авто-тест симулятора чачки
on:
  push:
    branches: ["main", "development", "feature/interactive-help"]
  pull_request:
    branches: ["main", "development", "feature/interactive-help"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v7.0.1

      - name: Установка Python 3.14
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.14"

      - name: Установка всех зависимостей [1 / 6]
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Установка инструментов (Ruff, MyPy, Bandit) [2 / 6]
        run: |
          python -m pip install mypy bandit ruff

      - name: Проверка синтаксиса  (Ruff) [3 / 6]
        run: |
          ruff check . --select=E9,F401,F821,F841,E225

      - name: Проверка порядка импортов (Ruff) [4 / 6]
        run: |
          ruff check . --select=I

      - name: Проверка типов (MyPy) [5 / 6]
        run: |
          mypy . --ignore-missing-imports

      - name: Проверка уязвимостей (Bandit) [6 / 6]
        run: |
          bandit -r . -ll
