name: Авто-тест симулятора чачки
on:
  push:
    branches: ["main", "development", "feature/tests"]
  pull_request:
    branches: ["main", "development", "feature/tests"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v7.0.1

      - name: Установка Python 3.14
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.14"

      - name: Установка всех зависимостей [1 / 6]
        run: |
          python -m pip install --upgrade pip
          python manage.py install

      - name: Установка инструментов (Ruff, MyPy, Bandit, Pytest) [2 / 6]
        run: |
          python -m pip install mypy bandit ruff pytest

      - name: Проверка синтаксиса и порядка импортов (Ruff) [3 / 6]
        run: |
          ruff check .

      - name: Проверка типов (MyPy) [4 / 6]
        run: |
          mypy . --ignore-missing-imports

      - name: Проверка уязвимостей (Bandit) [5 / 6]
        run: |
          bandit -r . -ll
      - name: Python-Тесты (pytest) [6 / 6]
        run: |
          pytest tests/
